= Sky's minecraft server wrapper
:experimental:
:source-highlighter: rouge
:source-language: shell
:icons: font
:toc: true
:sectanchors:
:star: *
Markus Dangl

== Overview

Experimental minecraft-server control script.
Features:

* Downloads fabric launcher
* Syncs mods with mods directory from a zip file
* Starts a fabric server
* Broadcasts server to LAN

== Missing features and bugs

* Does not handle terminal input nicely
* Missing proper logging (logs a bunch of crap and should output as json and to a file)

== TODO

Use a library instead of writing my own async handling -- candidates:

* https://twisted.org/

== Installing

Via git+pip:

[source,shell]
----
git clone git@github.com:xicesky/python-minecraft-scripts.git
cd python-minecraft-scripts
pip install .
minecraft-serverwrapper version
----

== Development

I recommend using VS Code:

* Install the Python extension
* Create a virtual environment (CTRL+SHIFT+P -> Python: Create Virtual Environment)
* Create a terminal (CTRL+SHIFT+P -> Python: Create Terminal) -- it should automatically activate the virtual environment
* Then follow the instructions below

Make sure you have python 3 (preferably 3.9 or later) and pip installed.

[source,shell]
----
# Install up-to-date pipenv
pip install pipenv --upgrade

# Install dependencies
pipenv install --dev

# Run tests
pipenv run pytest

# Install into current python environment
pipenv install -e .

----
