= Sky's minecraft server wrapper
:experimental:
:source-highlighter: rouge
:source-language: shell
:icons: font
:toc: true
:sectanchors:
:star: *
Markus Dangl

== Overview

Experimental minecraft-server control script.
Features:

* Downloads fabric launcher
* Syncs mods with mods directory from a zip file
* Starts a fabric server
* Broadcasts server to LAN

== Missing features and bugs

* Does not handle terminal input nicely
* Missing proper logging (logs a bunch of crap and should output as json and to a file)

== TODO

Use a library instead of writing my own async handling -- candidates:

* https://twisted.org/

== Installing

Via git+pip:

[source,shell]
----
git clone git@github.com:xicesky/python-minecraft-scripts.git
cd python-minecraft-scripts
pip install .
minecraft-serverwrapper version

----

== Basic usage

[source,shell]
----
# Set up a config file
minecraft-serverwrapper config print-default > minecraft-serverwrapper.yaml
# Edit the config file, remove all lines that you don't want to change
editor minecraft-serverwrapper.yaml
# Check the final configuration
minecraft-serverwrapper config print
# Aaaaaand go!
minecraft-serverwrapper run

----

== Development

I recommend using VS Code:

* Install the Python extension
* Create a virtual environment (CTRL+SHIFT+P -> Python: Create Virtual Environment)
* Create a terminal (CTRL+SHIFT+P -> Python: Create Terminal) -- it should automatically activate the virtual environment
* Then follow the instructions below

Make sure you have python 3.10 or later and pip installed.

[source,shell]
----
# Install up-to-date pipenv
pip install pipenv --upgrade

# Install dependencies
pipenv install --dev

# Run tests
pipenv run pytest

# Run script from the shell
pipenv run minecraft-serverwrapper version

# You can try to install the script in editable mode, but it doesn't always work well
pip install -e .

----
